### ISSUE TITLE
slim generator fails in one folder mode, because of ES6 modules

### ISSUE THREAD

**Issue by DracoBlue** [nikita-kit/generator-nikita#108]
```
Running "uglify:dist" (uglify) task
{ SyntaxError: Unexpected token: name (logging)
    at JS_Parse_Error.get (eval at <anonymous> (/home/travis/build/nikita-kit/nikita-generated-slim-one-folder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at formatError (util.js:644:15)
    at formatValue (util.js:550:18)
    at inspect (util.js:183:10)
    at exports.format (util.js:69:24)
    at Console.log (console.js:43:37)
    at /home/travis/build/nikita-kit/nikita-generated-slim-one-folder/node_modules/grunt-contrib-uglify/tasks/uglify.js:158:17
    at Array.forEach (native)
    at Object.<anonymous> (/home/travis/build/nikita-kit/nikita-generated-slim-one-folder/node_modules/grunt-contrib-uglify/tasks/uglify.js:77:16)
    at Object.<anonymous> (/home/travis/build/nikita-kit/nikita-generated-slim-one-folder/node_modules/grunt/lib/grunt/task.js:264:15)
  message: 'Unexpected token: name (logging)',
  filename: 'Test.jsb.js',
  line: 1,
  col: 7,
  pos: 7 }
>> Uglifying source src/AppBundle/Resources/public/js/Test.jsb.js failed.
Warning: Uglification failed.
Unexpected token: name (logging). 
Line 1 in src/AppBundle/Resources/public/js/Test.jsb.js
 Use --force to continue.
```

says https://travis-ci.org/nikita-kit/nikita-generated-slim-one-folder/jobs/281661280

@axten seems like uglifyjs cannot handle ES6 classes here. So far I don‘t think uglify should transform any file except the resulting main.js

**Comment by DracoBlue** [comment]
Fixed
